import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { DASHBOARD_LOCALE_COOKIE_NAME } from "./lib/localeConstants";
import {
  LocaleProvider,
  type Locale,
} from "./features/dashboard/stores/useLanguageStore";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const raw = cookieStore.get(DASHBOARD_LOCALE_COOKIE_NAME)?.value;
  const initialLocale: Locale = raw === "vi" ? "vi" : "en";

  return (
    <html lang={initialLocale}>
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <LocaleProvider initialLocale={initialLocale}>{children}</LocaleProvider>
      </body>
    </html>
  );
}
